// <auto-generated />
using FeedsWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedsWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215164915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("FeedsWebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Skye Lumen",
                            Username = "skye.lumen"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Lisa Nova",
                            Username = "lisa.nova"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Cypres Vale",
                            Username = "cypress.vale"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
